services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - front
      - back
      - static
    networks:
      - proxy

  front:
    image: fbansept/cda_2025_front:0.0.0
    expose:
      - "80"
    networks:
      - proxy

  back:
    image: fbansept/cda_2025_back:0.0.3
    expose:
      - "8080"
    depends_on:
      - db
    volumes:
      - ${PUBLIC_UPLOAD_FOLDER}:/public-upload
      - ${PRIVATE_UPLOAD_FOLDER}:/private-upload
    environment:
      - PUBLIC_UPLOAD_FOLDER=${PUBLIC_UPLOAD_FOLDER}
      - PRIVATE_UPLOAD_VOLUME=${PRIVATE_UPLOAD_FOLDER}
    networks:
      - proxy
      - backend

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    expose:
      - "3306"
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

  static:
    image: nginx:latest
    expose:
      - "80"
    volumes:
      - ${PUBLIC_UPLOAD_FOLDER}:/usr/share/nginx/html/images
      - ./nginx-static.conf:/etc/nginx/conf.d/default.conf
    environment:
      - PUBLIC_UPLOAD_FOLDER=${PUBLIC_UPLOAD_FOLDER}
    networks:
      - proxy

volumes:
  data:

networks:
  proxy:
  backend:

