services:

  front:
    image: fbansept/cda_2025_front:0.0.0
    ports:
      - "80:80"

  back:
    image: fbansept/cda_2025_back:0.0.3
    ports:
      - "8080:8080"

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - data:/var/lib/mysql

  static:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ${PUBLIC_UPLOAD_FOLDER}:/usr/share/nginx/html/images
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - .local.env
    environment:
      - PUBLIC_UPLOAD_FOLDER=${PUBLIC_UPLOAD_FOLDER}

volumes:
  data: