services:

  proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-static.conf:/etc/nginx/nginx.conf
      - ../certs:/etc/nginx/certs
    depends_on:
      - front
      - back
      - static

  front:
    image: fbansept/cda_2025_front:0.0.0
    expose:
      - "80"

  back:
    image: fbansept/cda_2025_back:0.0.3
    expose:
      - "8080"
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    expose:
      - "3306"
    volumes:
      - data:/var/lib/mysql

  static:
    image: nginx:latest
    expose:
      - "80"
    volumes:
      - ${PUBLIC_UPLOAD_FOLDER}:/usr/share/nginx/html/images
      - ./nginx-static.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - .local.env
    environment:
      - PUBLIC_UPLOAD_FOLDER=${PUBLIC_UPLOAD_FOLDER}

volumes:
  data: